"""add index

Revision ID: 4ffb8367067c
Revises: 1ebeadfbe2b1
Create Date: 2025-10-03 23:36:07.840812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ffb8367067c'
down_revision: Union[str, Sequence[str], None] = '1ebeadfbe2b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rating_movie_id'), 'rating', ['movie_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_movie_id'), table_name='rating')
    # ### end Alembic commands ###
