"""add vote_average

Revision ID: 95e3c94eba1d
Revises: 4ffb8367067c
Create Date: 2025-10-10 18:05:48.233862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95e3c94eba1d'
down_revision: Union[str, Sequence[str], None] = '4ffb8367067c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('vote_average', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'vote_average')
    # ### end Alembic commands ###
