"""add vote_count

Revision ID: cd77a4dbd38f
Revises: 95e3c94eba1d
Create Date: 2025-10-10 19:19:48.972896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cd77a4dbd38f'
down_revision: Union[str, Sequence[str], None] = '95e3c94eba1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('vote_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'vote_count')
    # ### end Alembic commands ###
